export const locales = ['pt', 'en', 'es'];
export const pageFiles = { home: 'index.html', solutions: 'solucoes.html', projects: 'projetos.html', about: 'sobre.html', contact: 'contato.html' };

export const copy = {
  pt: {
    locale: 'pt-BR', brand: 'Negócios e Tecnologia', skip: 'Ir para o conteúdo', menu: 'Abrir menu', closeMenu: 'Fechar menu', language: 'Idioma',
    nav: ['Soluções', 'Projetos', 'Sobre', 'Contato'], titles: {home: 'Sites, automações e CRM', solutions: 'Soluções', projects: 'Projetos', about: 'Sobre Felipe Chessa', contact: 'Vamos conversar'},
    description: 'Sites, automações e CRM para organizar seu negócio e atender melhor. Conheça as soluções e os projetos de Felipe Chessa.',
    talk: 'Vamos conversar', primary: 'Quero organizar meu negócio', viewSolutions: 'Ver soluções', allProjects: 'Conhecer os projetos', visit: 'Conhecer o produto', zoom: 'Ampliar imagem', close: 'Fechar', demo: 'Demonstração com dados fictícios',
    waMessage: 'Olá, Felipe! Quero conversar sobre como organizar e digitalizar meu negócio.', meetingMessage: 'Olá, Felipe! Gostaria de combinar um horário para uma reunião sobre meu negócio.',
    hero: { eyebrow: 'Para negócios que querem evoluir', title: 'Menos trabalho manual.', accent: 'Mais tempo para crescer.', description: 'Sites, automações e CRM para organizar seu negócio e atender melhor.', benefits: ['Mais organização', 'Processos mais eficientes', 'Crescimento sustentável'], scene: 'Da rotina dispersa à operação conectada', caption: 'Pessoas, processos e tecnologia. Conectados.' },
    solutionsIntro: {eyebrow: 'Do planejamento à execução', title: 'Soluções para cada etapa do negócio.', description: 'Um ponto de partida para o momento da sua empresa. Uma estrutura para os próximos passos.'},
    services: [
      {id: 'presenca-digital', icon: 'Monitor', title: 'Presença digital', short: 'Um site que apresenta seu valor e aproxima novos clientes.', description: 'Sites que traduzem o seu negócio, apresentam seus serviços e facilitam o primeiro contato. Do posicionamento à experiência no celular.', items: ['Sites institucionais e páginas de serviços', 'Portfólios e catálogos digitais', 'Contato integrado ao WhatsApp', 'Experiência responsiva e estrutura para busca'], cue: 'Seu negócio precisa ser encontrado.'},
      {id: 'automacao', icon: 'Workflow', title: 'Automação', short: 'Menos tarefas repetitivas. Mais espaço para o que importa.', description: 'Conecte etapas da rotina e diminua o trabalho repetitivo. A solução pode começar com um produto pronto ou ser desenhada para o seu processo.', items: ['Comunicação e rotinas no WhatsApp', 'Integração entre etapas e ferramentas', 'Fluxos de acompanhamento e tarefas', 'Automações ajustadas à operação'], cue: 'Sua rotina não precisa depender de você para tudo.'},
      {id: 'crm', icon: 'PanelsTopLeft', title: 'CRM e processos', short: 'Clientes, atendimentos e oportunidades em uma visão organizada.', description: 'Centralize o relacionamento com clientes e defina um jeito mais claro de trabalhar. O CRM acompanha o processo e o porte do negócio.', items: ['Organização de contatos e oportunidades', 'Atendimento e acompanhamento do cliente', 'Governança, responsabilidades e indicadores', 'Soluções para clínicas e negócios imobiliários'], cue: 'A informação certa, no lugar certo.'},
      {id: 'consultoria', icon: 'Compass', title: 'Consultoria de negócios', short: 'Entender a operação para escolher o próximo passo.', description: 'Diagnóstico, mapeamento e melhoria dos processos antes de escolher a tecnologia. Uma visão prática sobre o que existe hoje e o que precisa evoluir.', items: ['Diagnóstico da operação atual', 'Desenho do processo futuro', 'Estruturação de Customer Success', 'Plano de transformação digital'], cue: 'Primeiro, entender. Depois, transformar.'}
    ],
    projectsIntro: {eyebrow: 'Da ideia à operação', title: 'Soluções que já saíram do papel.', description: 'Produtos próprios e projetos que conectam presença digital, relacionamento e rotina de trabalho.'},
    projectFilters: ['Todos', 'Sites', 'Automação', 'CRM'], projectCount: 'projetos', projectCaption: 'Captura do produto', screenshotNote: 'As imagens são capturas das páginas públicas. O Lumina utiliza dados fictícios de demonstração.',
    projects: [
      {id:'lumina', name:'Lumina', category:'crm', label:'Gestão de clínicas', image:'lumina.webp', description:'Pacientes, agenda e procedimentos em uma operação mais conectada.', detail:'Sistema de gestão para clínicas, com painel de acompanhamento, organização da agenda, pacientes e procedimentos. A demonstração permite conhecer a experiência antes de conversar sobre a aplicação no seu negócio.', tags:['Agenda','Pacientes','Procedimentos'], link:'https://luminacrm-77.vercel.app/', cta:'Solicitar demonstração', demo:true},
      {id:'imobly', name:'Imobly', category:'crm', label:'Operação imobiliária', image:'imobly.webp', description:'Mais organização para o dia a dia de corretores e imobiliárias.', detail:'Fichas de locação, laudos de vistoria, recibos e relatórios de repasse reunidos em um sistema com identidade própria para cada operação.', tags:['Documentos','Vistorias','Relatórios'], link:'https://imobly-sistema.lovable.app/'},
      {id:'multienvio', name:'MultiEnvio', category:'automation', label:'Automação de WhatsApp', image:'multienvio.webp', description:'Uma ferramenta para organizar envios e comunicação pelo WhatsApp.', detail:'Aplicativo para Windows com seleção de contatos, importação de listas, personalização, agendamento e acompanhamento de envios. Uma solução pronta para rotinas de comunicação.', tags:['WhatsApp','Agendamento','Windows'], link:'https://multienvio.vercel.app/'},
      {id:'elbarbero', name:'E.L Barbero', category:'websites', label:'Presença digital', image:'elbarbero.webp', description:'Presença digital para aproximar pessoas do seu próximo imóvel.', detail:'Site de consultoria imobiliária com apresentação dos serviços, catálogo de imóveis, região de atuação e caminhos diretos para entrar em contato.', tags:['Site','Catálogo','Contato'], link:'https://elbarbero-two.vercel.app/', cta:'Visitar o site'}
    ],
    method: {eyebrow:'Um caminho com clareza', title:'O processo vem antes da ferramenta.', description:'Cada negócio tem um ponto de partida. O trabalho começa entendendo o seu.', steps:[['Entender','Conversamos sobre sua rotina, seus desafios e o que precisa mudar.'],['Desenhar','Mapeamos os processos e definimos prioridades e a solução adequada.'],['Construir','Configuramos ou desenvolvemos a solução e testamos os fluxos.'],['Colocar em prática','Preparamos as pessoas para usar a solução e seguir com a operação.']]},
    aboutTeaser: {eyebrow:'Experiência que vira prática', title:'Visão corporativa. Proximidade com o seu negócio.', description:'Sou Felipe Chessa. Conecto processos, relacionamento com clientes e tecnologia para transformar a forma como as empresas trabalham.', link:'Conheça minha trajetória', career:'Trajetória profissional'},
    about: {eyebrow:'Quem está por trás da Chessa', title:'Felipe Chessa.', accent:'Negócios, pessoas e tecnologia.', intro:'Atuo com transformação digital, CRM e processos de relacionamento com clientes. Meu trabalho começa ouvindo a operação e entendendo o que as pessoas precisam para trabalhar melhor.', paragraphs:['A experiência em ambientes corporativos me ensinou a olhar além da ferramenta: requisitos claros, processos bem desenhados e pessoas preparadas fazem parte da mesma entrega.','Na Chessa, aplico essa visão a negócios que precisam organizar sua rotina, construir sua presença digital ou dar um próximo passo com automação e CRM.'], careerTitle:'Uma trajetória em tecnologia e transformação.', careerDescription:'Minha experiência profissional inclui Indra (Minsait), Avanade e Bizapp. Essa trajetória sustenta minha atuação em diagnóstico, desenho funcional, implementação e treinamento.', careerNote:'Empresas que fazem parte da minha trajetória profissional.', expertise:['Dynamics 365 e Power Platform','Customer Service e omnichannel','Processos e transformação digital','Customer Success e governança'], credentials:'Conhecimento em evolução constante.', credentialsDescription:'Credenciais Microsoft listadas no meu perfil profissional, além de aprendizado em Copilot, agentes e segurança de dados com Purview.', linkedin:'Ver perfil e credenciais no LinkedIn', qualification:'Bacharel em Ciência e Tecnologia pela UNIFESP.', photoAlt:'Felipe Chessa em uma visita à Microsoft'},
    microsoft: {eyebrow:'Quando o negócio pede mais', title:'O potencial do ecossistema Microsoft.', description:'Possibilidades de aplicação para operações que precisam de processos integrados e maior estrutura. O escopo e o modelo de execução são avaliados conforme a necessidade de cada projeto.', reference:'Referência oficial', items:[['Power Apps','Aplicações para registrar informações, organizar demandas e acompanhar processos internos.'],['Dynamics 365 Sales','Gestão de contatos, oportunidades e etapas do relacionamento comercial.'],['Dynamics 365 Customer Service','Atendimentos, histórico de interações e direcionamento de demandas entre canais.']]},
    cta: {eyebrow:'Seu próximo passo', title:'O que está tomando tempo no seu negócio?', description:'Conte um pouco da sua rotina. Vamos entender onde a tecnologia pode ajudar.', button:'Conversar com Felipe'},
    contact: {eyebrow:'Vamos conversar', title:'Seu próximo passo começa com uma conversa.', description:'Conte o que você faz, o que está travando a rotina e onde quer chegar. Vamos encontrar um ponto de partida.', topic:'Sobre o que vamos conversar?', topics:['Organizar meu negócio','Criar ou melhorar meu site','Automatizar processos','Implantar um CRM','Projetos com tecnologia Microsoft'], whatsapp:'Conversar no WhatsApp', whatsappDescription:'Fale diretamente comigo sobre seu negócio.', meeting:'Agendar uma reunião', meetingDescription:'Combine um horário comigo pelo WhatsApp.', call:'Prefere ligar?', callDescription:'Uma conversa direta também pode ser o primeiro passo.', location:'São José dos Campos, SP', reach:'Do Brasil para novos horizontes.', reachDescription:'Atendimento remoto para Brasil, América Latina e Europa, em português, inglês e espanhol.', faqsTitle:'Antes de começarmos.', faqs:[['Você atende empresas pequenas?','Sim. A solução parte do momento do negócio. Pode ser um site, uma automação específica ou um CRM mais simples, com espaço para evoluir.'],['Posso contratar uma solução pronta ou personalizada?','As duas opções são possíveis. Há produtos já disponíveis e projetos sob demanda, definidos a partir dos seus processos.'],['Como funciona o orçamento?','Depois de entender sua necessidade, definimos o escopo, as etapas e uma proposta adequada ao projeto.'],['Como são conduzidos projetos maiores?','O escopo e o modelo de execução são avaliados caso a caso, considerando porte, complexidade e a estrutura necessária para entregar o projeto.']]},
    footer: {tagline:'Tecnologia com propósito. Negócios em movimento.', remote:'Brasil · América Latina · Europa', rights:'Todos os direitos reservados.', privacy:'Privacidade', privacyText:'Este site não utiliza ferramentas de publicidade nem formulários de coleta de dados. A preferência de idioma é salva somente no seu navegador. Ao abrir WhatsApp, LinkedIn ou os sites dos projetos, valem as políticas desses serviços.', backTop:'Voltar ao início'}
  },
  en: {
    locale:'en', brand:'Business & Technology', skip:'Skip to content', menu:'Open menu', closeMenu:'Close menu', language:'Language', nav:['Solutions','Projects','About','Contact'], titles:{home:'Websites, automation and CRM',solutions:'Solutions',projects:'Projects',about:'About Felipe Chessa',contact:'Let’s talk'},
    description:'Websites, automation and CRM to organize your business and serve your customers better. Explore Felipe Chessa’s solutions and projects.',
    talk:'Let’s talk',primary:'Let’s organize my business',viewSolutions:'Explore solutions',allProjects:'Explore the projects',visit:'Explore the product',zoom:'Enlarge image',close:'Close',demo:'Demo with fictional data',waMessage:'Hi Felipe! I would like to discuss how to organize and digitalize my business.',meetingMessage:'Hi Felipe! I would like to arrange a meeting to discuss my business.',
    hero:{eyebrow:'For businesses ready to evolve',title:'Less manual work.',accent:'More time to grow.',description:'Websites, automation and CRM to organize your business and serve your customers better.',benefits:['Better organization','More efficient processes','Sustainable growth'],scene:'From scattered tasks to a connected operation',caption:'People, processes and technology. Connected.'},
    solutionsIntro:{eyebrow:'From planning to delivery',title:'Solutions for every stage of your business.',description:'A starting point for where you are today. A foundation for what comes next.'},
    services:[
      {id:'presenca-digital',icon:'Monitor',title:'Digital presence',short:'A website that communicates your value and connects you with new customers.',description:'Websites that reflect your business, present your services and make it easy to get in touch. From positioning to the mobile experience.',items:['Business websites and service pages','Portfolios and digital catalogs','WhatsApp contact integration','Responsive experiences and search-ready structure'],cue:'Your business deserves to be found.'},
      {id:'automacao',icon:'Workflow',title:'Automation',short:'Fewer repetitive tasks. More room for what matters.',description:'Connect the steps in your daily work and reduce repetitive tasks. Start with an existing product or a solution designed around your process.',items:['WhatsApp communication workflows','Connections between tools and process steps','Follow-up and task workflows','Automation adapted to your operation'],cue:'Not every task needs to depend on you.'},
      {id:'crm',icon:'PanelsTopLeft',title:'CRM & processes',short:'Customers, service requests and opportunities in one organized view.',description:'Centralize customer relationships and establish a clearer way of working. The CRM fits your processes and the scale of your business.',items:['Contact and opportunity management','Customer service and follow-up','Governance, responsibilities and metrics','Solutions for clinics and real estate businesses'],cue:'The right information, in the right place.'},
      {id:'consultoria',icon:'Compass',title:'Business consulting',short:'Understand your operation and choose your next step.',description:'Assess, map and improve processes before choosing the technology. A practical view of where you are and what needs to evolve.',items:['Current operations assessment','Future process design','Customer Success foundations','Digital transformation roadmap'],cue:'Understand first. Then transform.'}
    ],
    projectsIntro:{eyebrow:'From idea to operation',title:'Ideas brought to life.',description:'Independent products and projects connecting digital presence, customer relationships and daily operations.'},projectFilters:['All','Websites','Automation','CRM'],projectCount:'projects',projectCaption:'Product screenshot',screenshotNote:'Images show public product pages. The Lumina preview contains fictional demonstration data.',
    projects:[
      {id:'lumina',name:'Lumina',category:'crm',label:'Clinic management',image:'lumina.webp',description:'Patients, appointments and procedures in a more connected operation.',detail:'Clinic management software with an overview dashboard, scheduling, patients and procedures. Explore a demonstration before discussing how it could fit your business.',tags:['Scheduling','Patients','Procedures'],link:'https://luminacrm-77.vercel.app/',cta:'Request a demo',demo:true},
      {id:'imobly',name:'Imobly',category:'crm',label:'Real estate operations',image:'imobly.webp',description:'A more organized workday for agents and real estate businesses.',detail:'Rental applications, inspection reports, receipts and owner statements in one system, with branding adapted to each operation.',tags:['Documents','Inspections','Reports'],link:'https://imobly-sistema.lovable.app/'},
      {id:'multienvio',name:'MultiEnvio',category:'automation',label:'WhatsApp automation',image:'multienvio.webp',description:'A tool to organize messaging and communication through WhatsApp.',detail:'A Windows application with contact selection, list imports, personalized messages, scheduling and delivery tracking. A ready-to-use solution for communication workflows.',tags:['WhatsApp','Scheduling','Windows'],link:'https://multienvio.vercel.app/'},
      {id:'elbarbero',name:'E.L Barbero',category:'websites',label:'Digital presence',image:'elbarbero.webp',description:'A digital presence connecting people with their next property.',detail:'A real estate consulting website with service information, property listings, coverage area and direct contact options.',tags:['Website','Listings','Contact'],link:'https://elbarbero-two.vercel.app/',cta:'Visit website'}
    ],
    method:{eyebrow:'A clear path forward',title:'Process comes before the tool.',description:'Every business has a starting point. Understanding yours is where the work begins.',steps:[['Understand','We discuss your daily work, challenges and what needs to change.'],['Design','We map your processes and define priorities and the right solution.'],['Build','We configure or develop the solution and test its workflows.'],['Put into practice','We prepare people to use the solution and take the operation forward.']]},
    aboutTeaser:{eyebrow:'Experience put into practice',title:'Corporate experience. A personal approach.',description:'I’m Felipe Chessa. I connect processes, customer relationships and technology to transform how businesses work.',link:'Explore my background',career:'Professional background'},
    about:{eyebrow:'The person behind Chessa',title:'Felipe Chessa.',accent:'Business, people and technology.',intro:'I work with digital transformation, CRM and customer relationship processes. My work starts by listening to the operation and understanding what people need to work better.',paragraphs:['Working in corporate environments has taught me to look beyond the tool: clear requirements, well-designed processes and prepared people are all part of the same delivery.','At Chessa, I bring this approach to businesses that need to organize daily work, build their digital presence or take the next step with automation and CRM.'],careerTitle:'A career in technology and transformation.',careerDescription:'My professional experience includes Indra (Minsait), Avanade and Bizapp. This background supports my work in assessment, functional design, implementation and training.',careerNote:'Companies that are part of my professional background.',expertise:['Dynamics 365 & Power Platform','Customer Service & omnichannel','Processes & digital transformation','Customer Success & governance'],credentials:'Knowledge that keeps evolving.',credentialsDescription:'Microsoft credentials listed on my professional profile, alongside ongoing learning in Copilot, agents and data security with Purview.',linkedin:'View profile and credentials on LinkedIn',qualification:'Bachelor of Science and Technology, UNIFESP.',photoAlt:'Felipe Chessa during a visit to Microsoft'},
    microsoft:{eyebrow:'When your business needs more',title:'The potential of the Microsoft ecosystem.',description:'Possible applications for operations that need integrated processes and a stronger foundation. Scope and delivery approach are assessed for each project.',reference:'Official reference',items:[['Power Apps','Applications to capture information, organize requests and track internal processes.'],['Dynamics 365 Sales','Manage contacts, opportunities and the stages of your sales relationships.'],['Dynamics 365 Customer Service','Service cases, interaction history and routing of requests across channels.']]},
    cta:{eyebrow:'Your next step',title:'What is taking up time in your business?',description:'Tell me about your daily work. Let’s explore where technology can help.',button:'Talk to Felipe'},
    contact:{eyebrow:'Let’s talk',title:'Your next step starts with a conversation.',description:'Tell me what you do, what is slowing you down and where you want to go. Let’s find a starting point.',topic:'What would you like to discuss?',topics:['Organizing my business','Creating or improving my website','Automating processes','Implementing a CRM','Projects with Microsoft technology'],whatsapp:'Chat on WhatsApp',whatsappDescription:'Talk to me directly about your business.',meeting:'Arrange a meeting',meetingDescription:'Find a time with me through WhatsApp.',call:'Prefer to call?',callDescription:'A direct conversation can be your first step, too.',location:'São José dos Campos, Brazil',reach:'From Brazil to new horizons.',reachDescription:'Remote services for Brazil, Latin America and Europe, in Portuguese, English and Spanish.',faqsTitle:'Before we begin.',faqs:[['Do you work with small businesses?','Yes. The solution starts with where the business is today. It could be a website, a specific automation or a simpler CRM, with room to evolve.'],['Can I choose a ready-made or custom solution?','Both are possible. There are existing products as well as custom projects shaped around your processes.'],['How do quotes work?','After understanding your needs, we define the scope, stages and a proposal appropriate to the project.'],['How are larger projects handled?','Scope and delivery approach are assessed individually, considering the size, complexity and resources the project requires.']]},
    footer:{tagline:'Purposeful technology. Business in motion.',remote:'Brazil · Latin America · Europe',rights:'All rights reserved.',privacy:'Privacy',privacyText:'This site uses no advertising tools or data collection forms. Your language preference is stored only in your browser. When you open WhatsApp, LinkedIn or project websites, their own policies apply.',backTop:'Back to top'}
  },
  es: {
    locale:'es',brand:'Negocios y Tecnología',skip:'Ir al contenido',menu:'Abrir menú',closeMenu:'Cerrar menú',language:'Idioma',nav:['Soluciones','Proyectos','Sobre mí','Contacto'],titles:{home:'Sitios web, automatización y CRM',solutions:'Soluciones',projects:'Proyectos',about:'Sobre Felipe Chessa',contact:'Conversemos'},
    description:'Sitios web, automatización y CRM para organizar tu negocio y atender mejor. Conoce las soluciones y los proyectos de Felipe Chessa.',
    talk:'Conversemos',primary:'Quiero organizar mi negocio',viewSolutions:'Ver soluciones',allProjects:'Conocer los proyectos',visit:'Conocer el producto',zoom:'Ampliar imagen',close:'Cerrar',demo:'Demostración con datos ficticios',waMessage:'¡Hola, Felipe! Quiero conversar sobre cómo organizar y digitalizar mi negocio.',meetingMessage:'¡Hola, Felipe! Me gustaría coordinar una reunión para conversar sobre mi negocio.',
    hero:{eyebrow:'Para negocios que quieren evolucionar',title:'Menos trabajo manual.',accent:'Más tiempo para crecer.',description:'Sitios web, automatización y CRM para organizar tu negocio y atender mejor.',benefits:['Más organización','Procesos más eficientes','Crecimiento sostenible'],scene:'De las tareas dispersas a una operación conectada',caption:'Personas, procesos y tecnología. Conectados.'},
    solutionsIntro:{eyebrow:'De la planificación a la ejecución',title:'Soluciones para cada etapa de tu negocio.',description:'Un punto de partida para el momento de tu empresa. Una base para los próximos pasos.'},
    services:[
      {id:'presenca-digital',icon:'Monitor',title:'Presencia digital',short:'Un sitio web que muestra tu valor y te acerca a nuevos clientes.',description:'Sitios web que reflejan tu negocio, presentan tus servicios y facilitan el primer contacto. Desde el posicionamiento hasta la experiencia móvil.',items:['Sitios institucionales y páginas de servicios','Portafolios y catálogos digitales','Contacto integrado con WhatsApp','Experiencia adaptable y estructura para buscadores'],cue:'Tu negocio necesita ser encontrado.'},
      {id:'automacao',icon:'Workflow',title:'Automatización',short:'Menos tareas repetitivas. Más espacio para lo que importa.',description:'Conecta las etapas de tu rutina y reduce el trabajo repetitivo. La solución puede comenzar con un producto listo o diseñarse para tu proceso.',items:['Comunicación y flujos en WhatsApp','Integración entre herramientas y etapas','Flujos de seguimiento y tareas','Automatización adaptada a la operación'],cue:'No todas las tareas tienen que depender de ti.'},
      {id:'crm',icon:'PanelsTopLeft',title:'CRM y procesos',short:'Clientes, atención y oportunidades en una vista organizada.',description:'Centraliza la relación con tus clientes y define una forma más clara de trabajar. El CRM acompaña los procesos y el tamaño de tu negocio.',items:['Organización de contactos y oportunidades','Atención y seguimiento del cliente','Gobernanza, responsabilidades e indicadores','Soluciones para clínicas y negocios inmobiliarios'],cue:'La información correcta, en el lugar correcto.'},
      {id:'consultoria',icon:'Compass',title:'Consultoría de negocios',short:'Entender la operación para elegir el próximo paso.',description:'Diagnóstico, mapeo y mejora de procesos antes de elegir la tecnología. Una visión práctica de la situación actual y de lo que debe evolucionar.',items:['Diagnóstico de la operación actual','Diseño del proceso futuro','Estructuración de Customer Success','Plan de transformación digital'],cue:'Primero, entender. Después, transformar.'}
    ],
    projectsIntro:{eyebrow:'De la idea a la operación',title:'Soluciones que ya son realidad.',description:'Productos propios y proyectos que conectan presencia digital, relación con clientes y trabajo diario.'},projectFilters:['Todos','Sitios web','Automatización','CRM'],projectCount:'proyectos',projectCaption:'Captura del producto',screenshotNote:'Las imágenes muestran páginas públicas de los productos. Lumina utiliza datos ficticios de demostración.',
    projects:[
      {id:'lumina',name:'Lumina',category:'crm',label:'Gestión de clínicas',image:'lumina.webp',description:'Pacientes, agenda y procedimientos en una operación más conectada.',detail:'Sistema de gestión para clínicas con panel de seguimiento, agenda, pacientes y procedimientos. La demostración permite conocer la experiencia antes de conversar sobre su aplicación en tu negocio.',tags:['Agenda','Pacientes','Procedimientos'],link:'https://luminacrm-77.vercel.app/',cta:'Solicitar demostración',demo:true},
      {id:'imobly',name:'Imobly',category:'crm',label:'Operación inmobiliaria',image:'imobly.webp',description:'Más organización para el día a día de agentes e inmobiliarias.',detail:'Fichas de alquiler, informes de inspección, recibos y liquidaciones para propietarios en un sistema con identidad propia para cada operación.',tags:['Documentos','Inspecciones','Informes'],link:'https://imobly-sistema.lovable.app/'},
      {id:'multienvio',name:'MultiEnvio',category:'automation',label:'Automatización de WhatsApp',image:'multienvio.webp',description:'Una herramienta para organizar envíos y comunicación por WhatsApp.',detail:'Aplicación para Windows con selección de contactos, importación de listas, personalización, programación y seguimiento de envíos. Una solución lista para rutinas de comunicación.',tags:['WhatsApp','Programación','Windows'],link:'https://multienvio.vercel.app/'},
      {id:'elbarbero',name:'E.L Barbero',category:'websites',label:'Presencia digital',image:'elbarbero.webp',description:'Presencia digital para acercar a las personas a su próximo inmueble.',detail:'Sitio de consultoría inmobiliaria con presentación de servicios, catálogo de inmuebles, zona de cobertura y opciones de contacto directo.',tags:['Sitio web','Catálogo','Contacto'],link:'https://elbarbero-two.vercel.app/',cta:'Visitar el sitio'}
    ],
    method:{eyebrow:'Un camino claro',title:'El proceso viene antes que la herramienta.',description:'Cada negocio tiene un punto de partida. El trabajo comienza entendiendo el tuyo.',steps:[['Entender','Conversamos sobre tu rutina, tus desafíos y lo que necesita cambiar.'],['Diseñar','Mapeamos los procesos y definimos prioridades y la solución adecuada.'],['Construir','Configuramos o desarrollamos la solución y probamos los flujos.'],['Poner en práctica','Preparamos a las personas para usar la solución y seguir con la operación.']]},
    aboutTeaser:{eyebrow:'Experiencia que se convierte en práctica',title:'Visión corporativa. Cercanía con tu negocio.',description:'Soy Felipe Chessa. Conecto procesos, relaciones con clientes y tecnología para transformar la forma en que trabajan las empresas.',link:'Conoce mi trayectoria',career:'Trayectoria profesional'},
    about:{eyebrow:'Quién está detrás de Chessa',title:'Felipe Chessa.',accent:'Negocios, personas y tecnología.',intro:'Trabajo con transformación digital, CRM y procesos de relación con clientes. Mi trabajo comienza escuchando la operación y entendiendo lo que las personas necesitan para trabajar mejor.',paragraphs:['La experiencia en entornos corporativos me enseñó a mirar más allá de la herramienta: requisitos claros, procesos bien diseñados y personas preparadas forman parte de una misma entrega.','En Chessa, aplico esta visión a negocios que necesitan organizar su rutina, construir su presencia digital o avanzar con automatización y CRM.'],careerTitle:'Una trayectoria en tecnología y transformación.',careerDescription:'Mi experiencia profesional incluye Indra (Minsait), Avanade y Bizapp. Esta trayectoria respalda mi trabajo en diagnóstico, diseño funcional, implementación y formación.',careerNote:'Empresas que forman parte de mi trayectoria profesional.',expertise:['Dynamics 365 y Power Platform','Customer Service y omnicanalidad','Procesos y transformación digital','Customer Success y gobernanza'],credentials:'Conocimiento en evolución constante.',credentialsDescription:'Credenciales Microsoft publicadas en mi perfil profesional, además de aprendizaje en Copilot, agentes y seguridad de datos con Purview.',linkedin:'Ver perfil y credenciales en LinkedIn',qualification:'Graduado en Ciencia y Tecnología por la UNIFESP.',photoAlt:'Felipe Chessa durante una visita a Microsoft'},
    microsoft:{eyebrow:'Cuando tu negocio necesita más',title:'El potencial del ecosistema Microsoft.',description:'Posibilidades de aplicación para operaciones que necesitan procesos integrados y una estructura más sólida. El alcance y la ejecución se evalúan según cada proyecto.',reference:'Referencia oficial',items:[['Power Apps','Aplicaciones para registrar información, organizar solicitudes y seguir procesos internos.'],['Dynamics 365 Sales','Gestión de contactos, oportunidades y etapas de la relación comercial.'],['Dynamics 365 Customer Service','Atención, historial de interacciones y asignación de solicitudes entre canales.']]},
    cta:{eyebrow:'Tu próximo paso',title:'¿Qué está consumiendo tiempo en tu negocio?',description:'Cuéntame sobre tu rutina. Veamos dónde puede ayudar la tecnología.',button:'Conversar con Felipe'},
    contact:{eyebrow:'Conversemos',title:'Tu próximo paso empieza con una conversación.',description:'Cuéntame qué haces, qué frena tu rutina y a dónde quieres llegar. Encontremos un punto de partida.',topic:'¿Sobre qué vamos a conversar?',topics:['Organizar mi negocio','Crear o mejorar mi sitio web','Automatizar procesos','Implementar un CRM','Proyectos con tecnología Microsoft'],whatsapp:'Conversar por WhatsApp',whatsappDescription:'Habla directamente conmigo sobre tu negocio.',meeting:'Coordinar una reunión',meetingDescription:'Acordemos un horario por WhatsApp.',call:'¿Prefieres llamar?',callDescription:'Una conversación directa también puede ser el primer paso.',location:'São José dos Campos, Brasil',reach:'Desde Brasil hacia nuevos horizontes.',reachDescription:'Atención remota para Brasil, América Latina y Europa, en portugués, inglés y español.',faqsTitle:'Antes de comenzar.',faqs:[['¿Trabajas con empresas pequeñas?','Sí. La solución parte del momento del negocio. Puede ser un sitio web, una automatización específica o un CRM más sencillo, con espacio para evolucionar.'],['¿Puedo contratar una solución lista o personalizada?','Ambas opciones son posibles. Hay productos disponibles y proyectos a medida, definidos a partir de tus procesos.'],['¿Cómo funciona el presupuesto?','Después de entender tu necesidad, definimos el alcance, las etapas y una propuesta adecuada al proyecto.'],['¿Cómo se gestionan los proyectos más grandes?','El alcance y la ejecución se evalúan caso por caso, considerando el tamaño, la complejidad y los recursos necesarios para entregar el proyecto.']]},
    footer:{tagline:'Tecnología con propósito. Negocios en movimiento.',remote:'Brasil · América Latina · Europa',rights:'Todos los derechos reservados.',privacy:'Privacidad',privacyText:'Este sitio no utiliza herramientas publicitarias ni formularios de recopilación de datos. Tu preferencia de idioma se guarda únicamente en tu navegador. Al abrir WhatsApp, LinkedIn o los sitios de los proyectos, se aplican sus propias políticas.',backTop:'Volver al inicio'}
  }
};
