import * as lucide from 'lucide-static';
import { copy, locales, pageFiles } from './content.mjs';

const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const icon = name => (lucide[name] || lucide.ArrowUpRight).replace('<svg', '<svg aria-hidden="true" focusable="false"');
const external = 'target="_blank" rel="noopener noreferrer"';
const wa = message => `https://wa.me/5511992876042?text=${encodeURIComponent(message)}`;
const links = ['solutions','projects','about','contact'];
const microsoftLinks = ['https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/model-driven-app-components','https://learn.microsoft.com/en-us/dynamics365/sales/overview','https://learn.microsoft.com/en-us/dynamics365/customer-service/implement/overview'];

export function renderPage(lang, page) {
  const t = copy[lang];
  const root = lang === 'pt' ? '' : '../';
  const asset = file => `${root}assets/${file}`;
  const url = (p, locale = lang) => `${root}${locale === 'pt' ? '' : `${locale}/`}${pageFiles[p]}`;
  const button = (label, href, variant = 'primary', ext = false) => `<a class="button button--${variant}" href="${escape(href)}" ${ext ? external : ''}>${escape(label)}${icon('ArrowUpRight')}</a>`;
  const textLink = (label, href, ext = false) => `<a class="text-link" href="${escape(href)}" ${ext ? external : ''}>${escape(label)}${icon('ArrowUpRight')}</a>`;
  const eyebrow = text => `<p class="eyebrow"><span></span>${escape(text)}</p>`;
  const sectionHeading = ({eyebrow:e, title, description}) => `<div class="section-heading"><div>${eyebrow(e)}<h2>${escape(title)}</h2></div>${description ? `<p class="section-description">${escape(description)}</p>` : ''}</div>`;
  const languageNav = () => `<div class="language-nav" role="group" aria-label="${t.language}">${locales.map(l => `<a href="${url(page,l)}" lang="${copy[l].locale}" hreflang="${copy[l].locale}" data-language="${l}" ${l===lang ? 'aria-current="true"' : ''} aria-label="${({pt:'Português',en:'English',es:'Español'})[l]}">${l.toUpperCase()}</a>`).join('')}</div>`;
  const logo = () => `<a class="brand" href="${url('home')}" aria-label="Chessa | ${t.brand}"><span class="brand-name">CHESSA<span class="brand-dot">.</span></span><span class="brand-description">${escape(t.brand)}</span></a>`;
  const header = `<a class="skip-link" href="#main">${t.skip}</a><header class="site-header"><div class="container header-inner">${logo()}<nav class="desktop-nav" aria-label="${lang==='pt'?'Navegação principal':lang==='en'?'Main navigation':'Navegación principal'}">${links.map((p,i)=>`<a href="${url(p)}" ${page===p?'aria-current="page"':''}>${t.nav[i]}</a>`).join('')}</nav><div class="header-actions">${languageNav()}<button class="menu-toggle icon-button" type="button" aria-expanded="false" aria-controls="mobile-nav" aria-label="${t.menu}" data-open-label="${t.menu}" data-close-label="${t.closeMenu}">${icon('Menu')}</button></div></div><nav id="mobile-nav" class="mobile-nav" hidden>${links.map((p,i)=>`<a href="${url(p)}" ${page===p?'aria-current="page"':''}>${t.nav[i]}${icon('ArrowUpRight')}</a>`).join('')}</nav></header>`;

  const serviceOverview = () => `<section class="section services-overview"><div class="container">${sectionHeading(t.solutionsIntro)}<div class="service-columns">${t.services.slice(0,3).map(s=>`<a href="${url('solutions')}#${s.id}" class="service-overview"><span class="service-icon">${icon(s.icon)}</span><div><h3>${s.title}</h3><p>${s.short}</p></div><span class="service-arrow">${icon('ArrowUpRight')}</span></a>`).join('')}</div></div></section>`;
  const projectImage = p => `<button class="project-image ${p.id}" type="button" data-lightbox="${asset(`projects/${p.image}`)}" data-caption="${escape(p.name)} — ${escape(p.demo ? t.demo : t.projectCaption)}" aria-label="${escape(`${t.zoom}: ${p.name}`)}"><img src="${asset(`projects/${p.image}`)}" alt="${escape(`${p.name} — ${p.label}`)}" width="1440" height="960" loading="lazy"><span class="zoom-icon">${icon('Maximize2')}</span>${p.demo?`<span class="image-label">${t.demo}</span>`:''}</button>`;
  const featuredProjects = () => `<section class="section section--soft"><div class="container">${sectionHeading(t.projectsIntro)}<div class="featured-grid">${t.projects.slice(0,2).map(p=>`<article class="project-card">${projectImage(p)}<div class="project-card-body"><p class="label">${p.label}</p><h3><a href="${url('projects')}#${p.id}">${p.name}${icon('ArrowUpRight')}</a></h3><p>${p.description}</p></div></article>`).join('')}</div><div class="section-end">${textLink(t.allProjects,url('projects'))}<span class="small-index">01 / 04</span></div></div></section>`;
  const method = () => `<section class="section method-section"><div class="container">${sectionHeading(t.method)}<ol class="method-grid">${t.method.steps.map(([title,description],i)=>`<li><span class="step-number">0${i+1}</span><h3>${title}</h3><p>${description}</p></li>`).join('')}</ol></div></section>`;
  const career = () => `<div class="career-brands" aria-label="${t.aboutTeaser.career}"><span>Indra <small>Minsait</small></span><span>Avanade <small>Accenture</small></span><span>Bizapp</span></div>`;
  const cta = () => `<section class="cta-band"><div class="container cta-inner"><div>${eyebrow(t.cta.eyebrow)}<h2>${t.cta.title}</h2><p>${t.cta.description}</p></div>${button(t.cta.button,wa(t.waMessage),'primary',true)}</div></section>`;
  const pageHero = (e,title,description,number) => `<section class="page-hero"><div class="container"><div class="page-hero-top">${eyebrow(e)}<span class="page-index">${number} / CHESSA</span></div><h1>${escape(title)}</h1><p class="page-lead">${escape(description)}</p></div></section>`;

  const pages = {
    home: () => `<section class="hero"><img class="hero-art" src="${asset('hero-tech.webp')}" alt="" width="1672" height="941" fetchpriority="high"><div class="hero-shade"></div><div class="container hero-inner"><div class="hero-copy">${eyebrow(t.hero.eyebrow)}<h1>${t.hero.title}<span>${t.hero.accent}</span></h1><p class="hero-description">${t.hero.description}</p><div class="hero-actions">${button(t.primary,wa(t.waMessage),'primary',true)}${button(t.viewSolutions,url('solutions'),'ghost')}</div></div><div class="hero-bottom"><ul class="hero-benefits">${t.hero.benefits.map((x,i)=>`<li>${icon(['ChartNoAxesCombined','Workflow','UsersRound'][i])}${x}</li>`).join('')}</ul><p class="hero-caption">${t.hero.caption}</p></div></div></section>${serviceOverview()}${featuredProjects()}${method()}<section class="section about-preview"><div class="container about-preview-inner"><div>${eyebrow(t.aboutTeaser.eyebrow)}<h2>${t.aboutTeaser.title}</h2></div><div><p class="large-paragraph">${t.aboutTeaser.description}</p>${textLink(t.aboutTeaser.link,url('about'))}<p class="label career-label">${t.aboutTeaser.career}</p>${career()}</div></div></section>${cta()}`,
    solutions: () => `${pageHero(t.solutionsIntro.eyebrow,t.solutionsIntro.title,t.solutionsIntro.description,'01')}<section class="section"><div class="container services-list">${t.services.map((s,i)=>`<article class="service-detail" id="${s.id}"><div class="service-number">0${i+1}<span>${icon(s.icon)}</span></div><div><p class="label">${s.cue}</p><h2>${s.title}</h2><p>${s.description}</p>${textLink(t.talk,wa(`${t.waMessage} ${s.title}.`),true)}</div><ul class="check-list">${s.items.map(x=>`<li>${icon('Check')}${x}</li>`).join('')}</ul></article>`).join('')}</div></section><section class="section microsoft-section"><div class="container">${sectionHeading(t.microsoft)}<div class="microsoft-grid">${t.microsoft.items.map(([title,description],i)=>`<article><span class="platform-mark">${['P','D','D'][i]}</span><h3>${title}</h3><p>${description}</p>${textLink(t.microsoft.reference,microsoftLinks[i],true)}</article>`).join('')}</div></div></section>${method()}${cta()}`,
    projects: () => `${pageHero(t.projectsIntro.eyebrow,t.projectsIntro.title,t.projectsIntro.description,'02')}<section class="section projects-section"><div class="container"><div class="project-toolbar"><div class="project-filters" role="group" aria-label="${t.nav[1]}">${t.projectFilters.map((label,i)=>`<button type="button" data-filter="${['all','websites','automation','crm'][i]}" aria-pressed="${i===0}">${label}</button>`).join('')}</div><span class="project-count" aria-live="polite"><span data-count>4</span> ${t.projectCount}</span></div><div class="project-list">${t.projects.map((p,i)=>`<article class="project-detail" id="${p.id}" data-category="${p.category}">${projectImage(p)}<div class="project-detail-copy"><span class="project-number">0${i+1} / ${p.label}</span><h2>${p.name}</h2><p class="project-lead">${p.description}</p><p>${p.detail}</p><ul class="tag-list">${p.tags.map(tag=>`<li>${tag}</li>`).join('')}</ul>${button(p.cta||t.visit,p.demo?wa(`${t.waMessage} Lumina.`):p.link,'dark',true)}${p.demo?textLink(t.visit,p.link,true):''}</div></article>`).join('')}</div><p class="image-note">${t.screenshotNote}</p></div></section>${cta()}`,
    about: () => `<section class="section about-hero"><div class="container about-grid"><div>${eyebrow(t.about.eyebrow)}<h1>${t.about.title}<span>${t.about.accent}</span></h1><p class="large-paragraph">${t.about.intro}</p><p>${t.about.paragraphs[0]}</p>${textLink(t.about.linkedin,'https://www.linkedin.com/in/felipe-chessa/',true)}</div><figure class="portrait"><img src="${asset('felipe-chessa.webp')}" width="640" height="640" alt="${t.about.photoAlt}" fetchpriority="high"><figcaption>Felipe Chessa<span>São José dos Campos · Brasil</span></figcaption></figure></div></section><section class="section section--soft"><div class="container career-section"><div>${eyebrow(t.aboutTeaser.career)}<h2>${t.about.careerTitle}</h2><p>${t.about.careerDescription}</p>${career()}<p class="caption">${t.about.careerNote}</p></div><div><p class="large-paragraph">${t.about.paragraphs[1]}</p><ul class="expertise-list">${t.about.expertise.map(x=>`<li>${icon('ArrowUpRight')}${x}</li>`).join('')}</ul><p class="qualification">${icon('GraduationCap')}${t.about.qualification}</p></div></div></section><section class="section"><div class="container credentials"><div>${eyebrow('Microsoft')}<h2>${t.about.credentials}</h2><p>${t.about.credentialsDescription}</p>${textLink(t.about.linkedin,'https://www.linkedin.com/in/felipe-chessa/',true)}</div><ul class="credential-list"><li><span>MB-230</span>Dynamics 365 Customer Service</li><li><span>MB-910</span>Dynamics 365 Fundamentals</li><li><span>PL-900</span>Power Platform Fundamentals</li></ul></div></section>${method()}${cta()}`,
    contact: () => `${pageHero(t.contact.eyebrow,t.contact.title,t.contact.description,'04')}<section class="section"><div class="container contact-grid"><div class="contact-main"><label for="contact-topic">${t.contact.topic}</label><select id="contact-topic">${t.contact.topics.map(x=>`<option value="${escape(x)}">${x}</option>`).join('')}</select><a class="contact-primary" data-contact-wa data-message="${escape(t.waMessage)}" href="${wa(t.waMessage)}" ${external}><span class="contact-icon">${icon('MessageCircle')}</span><span><strong>${t.contact.whatsapp}</strong><small>${t.contact.whatsappDescription}</small></span>${icon('ArrowUpRight')}</a><a class="contact-row" href="${wa(t.meetingMessage)}" ${external}>${icon('CalendarDays')}<span><strong>${t.contact.meeting}</strong><small>${t.contact.meetingDescription}</small></span>${icon('ArrowUpRight')}</a><a class="contact-row" href="tel:+5511992876042">${icon('Phone')}<span><strong>+55 (11) 99287-6042</strong><small>${t.contact.callDescription}</small></span>${icon('ArrowUpRight')}</a></div><aside class="contact-location">${icon('Globe2')}<h2>${t.contact.reach}</h2><p>${t.contact.reachDescription}</p><p class="location-line">${icon('MapPin')}${t.contact.location}</p><span class="language-list">Português / English / Español</span></aside></div></section><section class="section section--soft"><div class="container faq-layout"><h2>${t.contact.faqsTitle}</h2><div class="faq-list">${t.contact.faqs.map(([q,a])=>`<details><summary>${q}${icon('Plus')}</summary><p>${a}</p></details>`).join('')}</div></div></section>`
  };
  const footer = `<footer class="site-footer"><div class="container"><div class="footer-main"><div>${logo()}<p>${t.footer.tagline}</p></div><nav aria-label="${t.nav[3]}">${links.map((p,i)=>`<a href="${url(p)}">${t.nav[i]}</a>`).join('')}</nav><div class="footer-contact"><a href="tel:+5511992876042">+55 (11) 99287-6042</a><span>São José dos Campos, SP</span><span>${t.footer.remote}</span>${languageNav()}</div></div><div class="footer-bottom"><span>© ${new Date().getUTCFullYear()} Chessa. ${t.footer.rights}</span><button class="plain-button" data-dialog="privacy">${t.footer.privacy}</button><a href="#top" class="back-top" aria-label="${t.footer.backTop}">${icon('ArrowUp')}</a></div></div></footer><dialog id="privacy" class="privacy-dialog"><button class="dialog-close icon-button" data-close aria-label="${t.close}">${icon('X')}</button><h2>${t.footer.privacy}</h2><p>${t.footer.privacyText}</p></dialog><dialog id="lightbox" class="lightbox"><button class="dialog-close icon-button" data-close aria-label="${t.close}">${icon('X')}</button><figure><img alt="" width="1440" height="960"><figcaption></figcaption></figure></dialog>`;
  return `<!doctype html>
<html lang="${t.locale}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#091314"><meta name="description" content="${escape(t.description)}"><meta property="og:title" content="${escape(t.titles[page])} | Chessa"><meta property="og:description" content="${escape(t.description)}"><meta property="og:type" content="website"><meta name="color-scheme" content="light"><title>${escape(t.titles[page])} | Chessa</title><link rel="icon" href="${asset('favicon.svg')}" type="image/svg+xml"><link rel="preload" href="${asset('fonts/manrope-latin-wght-normal.woff2')}" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${asset('styles.css')}">${locales.map(l=>`<link rel="alternate" hreflang="${copy[l].locale}" href="${url(page,l)}">`).join('')}<script defer src="${asset('app.js')}"></script></head><body id="top" data-page="${page}" data-language="${lang}">${header}<main id="main">${pages[page]()}</main>${footer}</body></html>`;
}
